In [12]:
import pandas as pd
import re
import random
import numpy as np

# Sample dataframe
df = pd.read_csv('/Users/aldo.montinaro/Desktop/sci_stuff/ai_planning_by_european_countries.csv')


df.head()

,English name,Country,Start date,Yearly budget range
0,AUSTRIAN COUNCIL FOR ROBOTICS AND AI,Austria,2017.0,1M-5M
1,PLATFORM INDUSTRY 4.0 AUSTRIA,Austria,2015.0,Less than 1M
2,JOINT R&D PROJECT,Belgium,2017.0,1M-5M
3,PROSPECTIVE RESEARCH PROGRAMME,Belgium,2017.0,1M-5M
4,IMEC CORE FUNDING,Belgium,1984.0,More than 500M

In [13]:
# Drop rows where Start date is NaN
df = df.dropna(subset=['Start date'])

# Convert Start date column to integers
df['Start date'] = df['Start date'].astype(int)

In [14]:
# Function to convert budget range to integer
def convert_budget(budget_range):
    if budget_range == "Less than 1M":
        return random.randint(0, 999999)
    elif budget_range == "More than 500M":
        return 500000000
    else:
        lower, upper = budget_range.split('-')
        return random.randint(int(lower[:-1]) * 1000000, int(upper[:-1]) * 1000000)

# Apply function to Yearly budget range column
df['Yearly budget'] = df['Yearly budget range'].apply(convert_budget)

# Drop Yearly budget range column
df.drop(columns=['Yearly budget range'], inplace=True)

df

,English name,Country,Start date,Yearly budget
0,AUSTRIAN COUNCIL FOR ROBOTICS AND AI,Austria,2017,2722199
1,PLATFORM INDUSTRY 4.0 AUSTRIA,Austria,2015,22955
2,JOINT R&D PROJECT,Belgium,2017,4590303
3,PROSPECTIVE RESEARCH PROGRAMME,Belgium,2017,1468772
4,IMEC CORE FUNDING,Belgium,1984,500000000
...,...,...,...,...
247,GOVERNMENT ASSIGNMENT ON SMEs AND DATA AS A ST...,Sweden,2019,503770
248,GOVERNMENT ASSIGNMENT TO PROMOTE THE PUBLIC AD...,Sweden,2021,71419
249,AI Commission,Sweden,2024,272736
250,EU AI Act,Sweden,2024,629500
251,Work on upcoming Swedish Digitalisation Strate...,Sweden,2024,285690

In [15]:
df.to_csv('policy_budget.csv')